spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/base-donne
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: monirayad32@gmail.com
    password: siws xqay tvyr mkri
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
